In [2]:
import pandas as pd

df = pd.read_csv(r"E:\Smart-Irrigation-System\data\raw\irrigation_dataset.csv")

In [3]:
df.head()

,Soil_Type,Soil_pH,Soil_Moisture,Organic_Carbon,Electrical_Conductivity,Temperature_C,Humidity,Rainfall_mm,Sunlight_Hours,Wind_Speed_kmh,Crop_Type,Crop_Growth_Stage,Season,Irrigation_Type,Water_Source,Field_Area_hectare,Mulching_Used,Previous_Irrigation_mm,Region,Irrigation_Need
0,Clay,6.14,36.48,0.42,2.17,21.90,31.19,1167.70,4.01,1.97,Wheat,Vegetative,Rabi,Rainfed,Reservoir,4.73,Yes,1.98,South,Low
1,Silt,6.41,50.56,0.38,0.23,36.50,26.01,831.28,10.72,16.82,Maize,Flowering,Zaid,Canal,Groundwater,12.22,Yes,33.56,Central,Medium
2,Sandy,7.71,40.07,1.09,2.18,41.83,76.41,1844.45,7.75,19.03,Cotton,Harvest,Rabi,Drip,Reservoir,5.52,Yes,34.62,South,Low
3,Clay,5.96,12.75,1.56,0.40,37.22,43.32,306.26,8.90,11.44,Wheat,Sowing,Kharif,Canal,Reservoir,1.43,Yes,84.03,North,Medium
4,Clay,7.76,18.58,0.95,2.52,22.38,86.44,1875.63,10.39,11.26,Cotton,Sowing,Zaid,Canal,River,2.52,No,60.86,South,Medium

In [4]:
print(df.shape)

(10000, 20)

In [5]:
print(df.columns)

Index(['Soil_Type', 'Soil_pH', 'Soil_Moisture', 'Organic_Carbon',
       'Electrical_Conductivity', 'Temperature_C', 'Humidity', 'Rainfall_mm',
       'Sunlight_Hours', 'Wind_Speed_kmh', 'Crop_Type', 'Crop_Growth_Stage',
       'Season', 'Irrigation_Type', 'Water_Source', 'Field_Area_hectare',
       'Mulching_Used', 'Previous_Irrigation_mm', 'Region', 'Irrigation_Need'],
      dtype='object')

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 20 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   Soil_Type                10000 non-null  object
 1   Soil_pH                  10000 non-null  float64
 2   Soil_Moisture            10000 non-null  float64
 3   Organic_Carbon           10000 non-null  float64
 4   Electrical_Conductivity  10000 non-null  float64
 5   Temperature_C            10000 non-null  float64
 6   Humidity                 10000 non-null  float64
 7   Rainfall_mm              10000 non-null  float64
 8   Sunlight_Hours           10000 non-null  float64
 9   Wind_Speed_kmh           10000 non-null  float64
 10  Crop_Type                10000 non-null  object
 11  Crop_Growth_Stage        10000 non-null  object
 12  Season                   10000 non-null  object
 13  Irrigation_Type          10000 non-null  object
 14  Water_Source             10000 non-null  object
 15  Field_Area_hectare       10000 non-null  float64
 16  Mulching_Used            10000 non-null  object
 17  Previous_Irrigation_mm   10000 non-null  float64
 18  Region                   10000 non-null  object
 19  Irrigation_Need          10000 non-null  object
dtypes: float64(11), object(9)
memory usage: 1.5+ MB

In [7]:
df.describe()

,Soil_pH,Soil_Moisture,Organic_Carbon,Electrical_Conductivity,Temperature_C,Humidity,Rainfall_mm,Sunlight_Hours,Wind_Speed_kmh,Field_Area_hectare,Previous_Irrigation_mm
count,10000.000000,10000.000000,10000.000000,10000.000000,10000.000000,10000.000000,10000.000000,10000.000000,10000.000000,10000.000000,10000.000000
mean,6.487857,36.969207,0.944731,1.791963,26.991423,60.080339,1252.499420,7.518538,10.163545,7.598024,59.864122
std,0.979963,16.430845,0.372406,0.984202,8.664074,20.187973,715.582201,2.016077,5.670923,4.233919,34.483722
min,4.800000,8.000000,0.300000,0.100000,12.000000,25.000000,0.380000,4.000000,0.500000,0.300000,0.020000
25%,5.640000,22.860000,0.620000,0.940000,19.460000,42.855000,634.155000,5.760000,5.160000,3.950000,30.160000
50%,6.470000,37.240000,0.950000,1.780000,27.090000,60.040000,1250.335000,7.560000,10.190000,7.540000,59.630000
75%,7.350000,50.940000,1.260000,2.650000,34.500000,77.705000,1880.265000,9.260000,15.100000,11.202500,90.030000
max,8.200000,65.000000,1.600000,3.500000,42.000000,95.000000,2499.690000,11.000000,20.000000,15.000000,119.990000

In [8]:
df.sample(10)

,Soil_Type,Soil_pH,Soil_Moisture,Organic_Carbon,Electrical_Conductivity,Temperature_C,Humidity,Rainfall_mm,Sunlight_Hours,Wind_Speed_kmh,Crop_Type,Crop_Growth_Stage,Season,Irrigation_Type,Water_Source,Field_Area_hectare,Mulching_Used,Previous_Irrigation_mm,Region,Irrigation_Need
33,Loamy,6.84,60.37,1.52,1.46,26.64,80.47,71.19,5.48,3.37,Rice,Harvest,Rabi,Rainfed,Groundwater,1.24,Yes,68.07,North,Low
9482,Sandy,4.85,22.65,1.44,0.24,13.11,43.94,1759.53,6.63,12.58,Maize,Sowing,Kharif,Sprinkler,Groundwater,4.83,Yes,104.22,East,Low
2577,Sandy,7.23,11.24,0.71,0.58,25.33,50.82,825.97,7.35,19.59,Wheat,Flowering,Rabi,Rainfed,Reservoir,4.81,No,107.62,North,Medium
3645,Silt,6.33,35.94,0.86,2.68,22.98,27.54,1826.75,7.86,18.16,Potato,Vegetative,Zaid,Drip,Groundwater,9.24,No,32.15,East,Medium
4761,Clay,5.30,63.58,0.89,1.16,41.12,74.43,2075.71,7.93,14.38,Potato,Harvest,Kharif,Drip,Reservoir,1.33,No,108.77,Central,Low
141,Sandy,5.23,63.95,1.10,3.07,35.45,52.10,2293.10,4.23,6.91,Rice,Harvest,Rabi,Drip,Reservoir,10.30,Yes,34.05,Central,Low
8229,Silt,5.72,12.50,0.52,0.11,20.41,87.99,1420.72,8.84,19.58,Cotton,Flowering,Rabi,Drip,Reservoir,3.98,Yes,10.44,Central,Medium
692,Sandy,7.12,38.24,1.55,2.25,24.23,68.54,306.19,8.74,6.03,Potato,Harvest,Zaid,Canal,Reservoir,10.75,No,19.07,East,Low
3246,Silt,5.53,13.62,0.55,2.74,26.07,62.45,1100.94,10.44,12.05,Wheat,Vegetative,Kharif,Canal,Groundwater,9.30,Yes,61.42,East,Medium
7134,Clay,5.19,27.94,0.64,2.42,41.65,31.65,977.55,7.54,13.29,Wheat,Sowing,Zaid,Rainfed,Rainwater,10.72,No,28.67,West,Low